'use strict';
const $=id=>document.getElementById(id);
const FIELDS={application_date:'填写日期',expense_unit:'报销单位',payee:'收款单位',account:'账号',bank:'开户行',amount:'金额',reason:'付款原因',attachments:'附件张数',maker:'制单人'};
const KEY='payment-request-browser-v1';
const EXPENSE_DEFAULT_VERSION=1;
const DEFAULT_EXPENSE_UNIT='深圳春风米逸科技有限公司';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const defaults=()=>({application_date:today(),expense_unit:DEFAULT_EXPENSE_UNIT,payee:'',account:'',bank:'',amount:'',reason:'',attachments:'1',maker:'',team:''});
let state={version:1,history:[],contacts:[],draft:null},readable=true,activeId=null,busy=false,ocrValues=null,ocrURL=null;
const tell=text=>{$('message').textContent=text;};
function cents(text){if(!/^\d+(\.\d{1,2})?$/.test(text))throw Error('金额须为正数，且最多保留两位小数。');const [a,b='']=text.split('.');return BigInt(a)*100n+BigInt(b.padEnd(2,'0'));}
function decimal(c){return `${c/100n}.${String(c%100n).padStart(2,'0')}`;}
function upperMoney(text){let n;try{n=cents(text);}catch{return ''; }if(n>=100000000000000n)return '';const chars='零壹贰叁肆伍陆柒捌玖',units=['','拾','佰','仟'];const group=n=>{let s='',zero=false;for(let i=3;i>=0;i--){const d=Math.floor(n/10**i)%10;if(d){if(zero)s+='零';s+=chars[d]+units[i];zero=false;}else if(s)zero=true;}return s;};let yuan=n/100n,parts=[],x=yuan;while(x){parts.unshift(Number(x%10000n));x/=10000n;}let s='',pending=false;parts.forEach((g,i)=>{const pos=parts.length-1-i;if(g){if(s&&(pending||g<1000))s+='零';s+=group(g)+['','万','亿'][pos];pending=false;}else if(s)pending=true;});s=(s||'零')+'元';const j=Number(n%100n/10n),f=Number(n%10n);if(!j&&!f)return s+'整';if(j)s+=chars[j]+'角';else if(yuan&&f)s+='零';if(f)s+=chars[f]+'分';return s;}
function validate(data,stored=false){const clean={};for(const [k,label] of Object.entries(FIELDS)){clean[k]=String(data[k]??'').trim();if(!clean[k])throw Error(`请填写${label}。`);}clean.team=String(data.team??'').trim();const d=new Date(clean.application_date+'T12:00:00');if(!/^\d{4}-\d{2}-\d{2}$/.test(clean.application_date)||!Number.isFinite(+d)||`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`!==clean.application_date)throw Error('填写日期无效。');const c=cents(clean.amount);if(c<=0n||c>=100000000000000n)throw Error('金额必须大于零且小于 1 万亿元。');clean.amount=decimal(c);if(!/^\d{1,4}$/.test(clean.attachments)||Number(clean.attachments)>9999)throw Error('附件张数须为 0–9999 的整数。');for(const [k,v] of Object.entries(clean))if(v.length>(stored?10000:(k==='reason'?300:150)))throw Error(`${FIELDS[k]||'团队'}内容过长。`);return clean;}
function validState(value){if(!value||value.version!==1||!Array.isArray(value.history)||!Array.isArray(value.contacts)||value.history.length>20000||value.contacts.length>10000)throw Error('备份格式无效。');for(const r of value.history){if(typeof r.id!=='string'||typeof r.created!=='string'||!Number.isFinite(Date.parse(r.created)))throw Error('记录格式无效。');r.data=validate(r.data,true);if(r.archives!==undefined){if(!Array.isArray(r.archives)||r.archives.length>1000)throw Error('原始文件记录无效。');for(const a of r.archives)if(!a||typeof a.key!=='string'||a.key.length>200||typeof a.name!=='string'||a.name.length>300||!['xlsx','pdf','png'].includes(a.format))throw Error('原始文件记录无效。');}}for(const c of value.contacts){if(!c||!c.payee?.trim()||['payee','account','bank'].some(k=>typeof c[k]!=='string'||c[k].length>10000))throw Error('收款方格式无效。');}if(value.draft!==null&&typeof value.draft!=='object')throw Error('草稿格式无效。');return value;}
function load(){try{const raw=localStorage.getItem(KEY);if(raw)state=validState(JSON.parse(raw));}catch{readable=false;$('fatal').textContent='无法读取已有浏览器记录。为防止覆盖，暂时停止保存和导出。请检查浏览器存储设置或恢复数据。';}}
function persist(next){if(!readable)throw Error('当前无法读取浏览器存储。');try{localStorage.setItem(KEY,JSON.stringify(next));}catch{throw Error('浏览器保存失败，可能存储空间不足。请先备份已有数据。');}state=next;}
function values(){return Object.fromEntries(new FormData($('application')));}
function fill(data){for(const input of $('application').elements){if(input.name)input.value=data[input.name]??'';}refreshPreview();}
function control(k,label,value='',prefix=''){const wrapper=document.createElement('label');wrapper.textContent=label;wrapper.className=k==='reason'?'wide':'';const el=document.createElement(k==='reason'?'textarea':'input');el.name=k;el.id=prefix+k;el.value=value;el.maxLength=k==='reason'?300:150;if(k==='application_date')el.type='date';if(['amount','attachments'].includes(k))el.inputMode=k==='amount'?'decimal':'numeric';if(k==='account')el.inputMode='numeric';if(k==='payee')el.setAttribute('list','payee-options');wrapper.append(el);return wrapper;}
for(const [k,label] of Object.entries(FIELDS))$('fields').append(control(k,label));
function page(name){for(const section of document.querySelectorAll('.page'))section.hidden=section.id!==name+'-page';for(const button of document.querySelectorAll('nav button'))button.classList.toggle('active',button.dataset.page===name);$('page-title').textContent={form:'填写申请',ocr:'识图填充',history:'历史记录',contacts:'收款方通讯录',stats:'台账统计'}[name];if(name==='history')renderHistory();if(name==='contacts')renderContacts();if(name==='stats')renderStats();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));
function reset(){activeId=null;fill(defaults());persist({...state,draft:null});tell('已新建申请。');page('form');}
$('new').onclick=()=>run(()=>{if(state.draft&&Object.values(state.draft).some(x=>x)&&!confirm('新建申请将清空当前表单，是否继续？'))return;reset();});
$('application').addEventListener('input',()=>{refreshPreview();run(()=>persist({...state,draft:values()}));});
$('application').addEventListener('submit',e=>e.preventDefault());
async function run(fn){try{return await fn();}catch(e){tell(e.message||'操作失败，请重试。');return null;}}
function safeStem(data){let team=(data.team||'').slice(0,20),reason=(data.reason||'付款申请').slice(0,40);if(team&&reason.includes(team))team='';return (team?team+'-':'')+reason.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/｜/g,'-').replace(/[. ]+$/,'');}
function duplicate(data){return state.history.filter(r=>r.id!==activeId&&r.data.payee===data.payee&&cents(r.data.amount)===cents(data.amount)&&Date.now()-Date.parse(r.created)<=30*86400000);}
function recordExport(data,formats){const existing=state.history.find(r=>r.id===activeId&&JSON.stringify(r.data)===JSON.stringify(data));const record=existing?{...existing,formats:[...new Set([...(existing.formats||[]),...formats])]}:{id:crypto.randomUUID(),created:new Date().toISOString(),data,formats};const contacts=[...state.contacts];if(!contacts.some(c=>c.payee===data.payee&&c.account===data.account&&c.bank===data.bank))contacts.push({payee:data.payee,account:data.account,bank:data.bank});persist({...state,history:existing?state.history.map(r=>r.id===existing.id?record:r):[record,...state.history],contacts,draft:null});activeId=record.id;refreshOptions();}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function textBox(ctx,text,x,y,w,h,size=26,align='left'){text=String(text??'');let lines=[],font=size;for(;font>=14;font--){ctx.font=`${font}px "Microsoft YaHei",sans-serif`;lines=[];for(const paragraph of text.split('\n')){let line='';for(const ch of paragraph){if(ctx.measureText(line+ch).width>w-20&&line){lines.push(line);line=ch;}else line+=ch;}lines.push(line);}if(lines.length*font*1.4<=h-14)break;}ctx.textBaseline='middle';ctx.textAlign=align;lines.forEach((line,i)=>ctx.fillText(line,align==='center'?x+w/2:x+10,y+(h-lines.length*font*1.4)/2+font*.7+i*font*1.4));}
function documentCanvas(data){return templateCanvas(data);}
function refreshPreview(){const source=documentCanvas(values()),canvas=$('preview');canvas.width=source.width;canvas.height=source.height;canvas.getContext('2d').drawImage(source,0,0);}
async function excelBlob(data){return originalTemplateWorkbook(data);}
async function outputBlob(data,format){if(format==='xlsx')return excelBlob(data);const canvas=documentCanvas(data);if(format==='png')return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('无法生成图片')),'image/png'));if(!window.jspdf)throw Error('PDF 组件未加载，请刷新网页。');const doc=new window.jspdf.jsPDF({orientation:'landscape',unit:'mm',format:'a4'});const size=templateCoordinates(),ratio=TEMPLATE_MODEL.scale/100*25.4/72;const w=size.width*ratio,h=size.height*ratio;doc.addImage(canvas,'PNG',(297-w)/2,TEMPLATE_MODEL.margins.top*25.4,w,h,undefined,'FAST');return doc.output('blob');}
function zipFiles(files){const encoder=new TextEncoder();let offset=0,local=[],directory=[];const crc=bytes=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;};const header=(size)=>{const a=new Uint8Array(size);return [a,new DataView(a.buffer)];};for(const f of files){const name=encoder.encode(f.name),bytes=f.bytes,checksum=crc(bytes);const [a,v]=header(30);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,checksum,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,name.length,true);local.push(a,name,bytes);const [b,w]=header(46);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint32(16,checksum,true);w.setUint32(20,bytes.length,true);w.setUint32(24,bytes.length,true);w.setUint16(28,name.length,true);w.setUint32(42,offset,true);directory.push(b,name);offset+=30+name.length+bytes.length;}const size=directory.reduce((n,a)=>n+a.length,0),[end,e]=header(22);e.setUint32(0,0x06054b50,true);e.setUint16(8,files.length,true);e.setUint16(10,files.length,true);e.setUint32(12,size,true);e.setUint32(16,offset,true);return new Blob([...local,...directory,end],{type:'application/zip'});}
async function exportData(formats,filename){if(busy)return;if(!formats.length)throw Error('至少选择一种格式。');if(!readable)throw Error('浏览器存储不可用，未开始导出。');const data=validate(values(),state.history.some(r=>r.id===activeId&&r.source==='desktop')),matches=duplicate(data);if(matches.length&&!confirm(`近 30 天已有 ${matches.length} 笔同一收款单位、同样金额的申请，仍要导出吗？`))return;busy=true;document.querySelectorAll('[data-export],#confirm-all,#all').forEach(b=>b.disabled=true);try{tell('正在生成文件…');const stem=(filename||safeStem(data)).replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[. ]+$/,'')||'付款申请';const files=[];for(const format of formats){const blob=await outputBlob(data,format);files.push({name:stem+'.'+format,blob,bytes:new Uint8Array(await blob.arrayBuffer())});}recordExport(data,formats);if(files.length===1)download(files[0].blob,files[0].name);else download(zipFiles(files),stem+'.zip');$('multi').close();tell('文件已生成并交给浏览器下载，申请已加入历史记录。');}finally{busy=false;document.querySelectorAll('[data-export],#confirm-all,#all').forEach(b=>b.disabled=false);}}
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>run(()=>exportData([b.dataset.export])));
$('all').onclick=()=>run(()=>{validate(values(),state.history.some(r=>r.id===activeId&&r.source==='desktop'));$('filename').value=safeStem(values());$('multi').showModal();});
$('confirm-all').onclick=()=>run(()=>exportData([...$('multi').querySelectorAll('input[name="format"]:checked')].map(e=>e.value),$('filename').value));
$('copy').onclick=()=>run(async()=>{await navigator.clipboard.writeText(Object.entries(FIELDS).filter(([k])=>values()[k]).map(([k,v])=>`${v}：${values()[k]}`).join('\n'));tell('申请信息已复制。');});
function empty(parent,text){const p=document.createElement('p');p.className='muted';p.textContent=text;parent.append(p);}
function button(text,action){const b=document.createElement('button');b.textContent=text;b.onclick=()=>run(action);return b;}
function renderHistory(){const list=$('history-list');list.replaceChildren();const q=$('search').value.trim().toLowerCase(),records=state.history.filter(r=>Object.values(r.data).join(' ').toLowerCase().includes(q));if(!records.length)empty(list,'暂无符合条件的记录。');for(const r of records){const row=document.createElement('div');row.className='record';const info=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('p');title.textContent=`${r.data.payee} · ¥ ${r.data.amount}`;detail.textContent=`${r.data.application_date} · ${r.data.reason.length>100?r.data.reason.slice(0,100)+'…':r.data.reason}`;detail.title=r.data.reason;info.append(title,detail);row.append(info,button('载入并查看',()=>{activeId=r.id;fill(r.data);persist({...state,draft:r.data});page('form');tell('已载入历史申请。修改内容后导出会新增记录。');}));const archives=document.createElement('div');archives.className='actions';for(const archive of r.archives||[])archives.append(button('下载原始 '+archive.format.toUpperCase(),()=>downloadDesktopFile(archive)));if(archives.children.length)row.append(archives);list.append(row);}}
$('search').oninput=renderHistory;
function refreshOptions(){const list=$('payee-options');list.replaceChildren();for(const name of new Set(state.contacts.map(c=>c.payee))){const opt=document.createElement('option');opt.value=name;list.append(opt);}}
const payeeInput=$('payee');payeeInput.addEventListener('change',()=>{const matches=state.contacts.filter(c=>c.payee===payeeInput.value);if(matches.length===1){$('account').value=matches[0].account;$('bank').value=matches[0].bank;refreshPreview();run(()=>persist({...state,draft:values()}));}else if(matches.length>1){page('contacts');tell('该单位有多个账号，请选择需要使用的账户。');}});
function renderContacts(){const list=$('contact-list');list.replaceChildren();if(!state.contacts.length)empty(list,'还没有收款方，成功导出后会自动加入，也可以手工添加。');for(const contact of state.contacts){const row=document.createElement('div');row.className='record';const info=document.createElement('div'),name=document.createElement('strong'),detail=document.createElement('p');name.textContent=contact.payee;detail.textContent=`${contact.account} · ${contact.bank}`;info.append(name,detail);row.append(info,button('用于申请',()=>{$('payee').value=contact.payee;$('account').value=contact.account;$('bank').value=contact.bank;refreshPreview();persist({...state,draft:values()});page('form');tell('已带出收款单位、账号和开户行。');}));list.append(row);}}
$('contact-form').onsubmit=e=>{e.preventDefault();run(()=>{const data=Object.fromEntries(new FormData(e.target));if(['payee','account','bank'].some(k=>!data[k].trim()))throw Error('请完整填写收款方信息。');const contacts=state.contacts.filter(c=>!(c.payee===data.payee&&c.account===data.account));contacts.push(data);persist({...state,contacts});refreshOptions();renderContacts();e.target.reset();tell('收款方已保存。');});};
function table(parent,headers,rows){parent.replaceChildren();if(!rows.length)return empty(parent,'暂无数据。');const wrap=document.createElement('div');wrap.className='table-wrap';const t=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr');headers.forEach(h=>{const th=document.createElement('th');th.textContent=h;tr.append(th);});head.append(tr);t.append(head);const body=document.createElement('tbody');for(const row of rows){const r=document.createElement('tr');row.forEach(v=>{const td=document.createElement('td');td.textContent=v;r.append(td);});body.append(r);}t.append(body);wrap.append(t);parent.append(wrap);}
function summary(key){const map=new Map();for(const r of state.history){const k=key(r.data),v=map.get(k)||{count:0,total:0n};v.count++;v.total+=cents(r.data.amount);map.set(k,v);}return [...map].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,v])=>[k,v.count,'¥ '+decimal(v.total)]);}
function renderStats(){const cards=$('stat-cards');cards.replaceChildren();const total=state.history.reduce((sum,r)=>sum+cents(r.data.amount),0n);for(const [label,value] of [['累计申请 / 笔',state.history.length],['累计申请金额 / 元',decimal(total)],['收款单位 / 家',new Set(state.history.map(r=>r.data.payee)).size]]){const card=document.createElement('article'),title=document.createElement('span'),v=document.createElement('strong');title.textContent=label;v.textContent=value;card.append(title,v);cards.append(card);}table($('month-stats'),['月份','申请笔数','申请金额'],summary(d=>d.application_date.slice(0,7)));table($('payee-stats'),['收款单位','申请笔数','申请金额'],summary(d=>d.payee));}
$('csv').onclick=()=>run(()=>{const quote=s=>'"'+String(/^[=+\-@\t\r]/.test(String(s))?"'"+s:s).replace(/"/g,'""')+'"';const rows=[Object.values(FIELDS),...state.history.map(r=>Object.keys(FIELDS).map(k=>k==='account'?"'"+r.data[k]:r.data[k]))];download(new Blob(['\ufeff'+rows.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'付款申请台账.csv');tell('台账已导出，账号按文本保存。');});
$('backup').onclick=()=>run(()=>{if(!readable)throw Error('无法读取记录，未生成备份。');download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'付款申请备份-'+today()+'.json');});
$('restore').onchange=e=>run(async()=>{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024)throw Error('备份文件不能超过 20 MB。');const incoming=validState(JSON.parse(await file.text()));if(!readable)throw Error('现有存储数据无法读取，请先检查浏览器存储。');const ids=new Set(state.history.map(r=>r.id)),contacts=[...state.contacts];for(const c of incoming.contacts)if(!contacts.some(x=>x.payee===c.payee&&x.account===c.account&&x.bank===c.bank))contacts.push(c);persist({...state,history:[...state.history,...incoming.history.filter(r=>!ids.has(r.id))],contacts});refreshOptions();renderHistory();tell('备份已合并恢复，现有记录保留。');e.target.value='';});
function redBoxes(canvas){const {width:w,height:h}=canvas,img=canvas.getContext('2d').getImageData(0,0,w,h).data,mask=new Uint8Array(w*h),queue=new Int32Array(w*h),out=[];for(let i=0;i<mask.length;i++){const p=i*4;mask[i]=img[p]>=215&&img[p+1]<=155&&img[p+2]<=155?1:0;}for(let i=0;i<mask.length;i++){if(!mask[i])continue;let head=0,tail=1,minx=w,miny=h,maxx=0,maxy=0;queue[0]=i;mask[i]=0;while(head<tail){const p=queue[head++],x=p%w,y=Math.floor(p/w);minx=Math.min(minx,x);maxx=Math.max(maxx,x);miny=Math.min(miny,y);maxy=Math.max(maxy,y);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const xx=x+dx,yy=y+dy;if(xx<0||xx>=w||yy<0||yy>=h)continue;const j=yy*w+xx;if(mask[j]){mask[j]=0;queue[tail++]=j;}}}const bw=maxx-minx+1,bh=maxy-miny+1;if(bw<50||bh<18||tail<2*(bw+bh)*.2)continue;const edge=[0,0,0,0];for(let k=0;k<tail;k++){const x=queue[k]%w,y=Math.floor(queue[k]/w);if(y-miny<5)edge[0]++;if(maxy-y<5)edge[1]++;if(x-minx<5)edge[2]++;if(maxx-x<5)edge[3]++;}if(edge[0]<bw*.2||edge[1]<bw*.2||edge[2]<bh*.2||edge[3]<bh*.2)continue;out.push({x:minx,y:miny,w:bw,h:bh});}return out.sort((a,b)=>a.y-b.y||a.x-b.x);}
function parseOCR(results,imageHeight){const choices={payee:[],account:[],bank:[],amount:[],reason:[],team:[]};let title='';results.forEach(({text,box},index)=>{const clean=text.replace(/[ \t]/g,''),lines=clean.split('\n').filter(Boolean);if(index===0&&box.y<imageHeight*.35){title=lines.join('');return;}if(/银行|开户|收款|账户|账号/.test(clean)){for(let i=0;i<lines.length;i++){const line=lines[i],next=lines[i+1]||'';const a=line.match(/(?:账号|账户号码|账户号)[：:]?([\d\s-]{8,})/);if(a)choices.account.push(a[1].replace(/\D/g,''));else if(/账号|账户号/.test(line)&&/^\d{8,}$/.test(next))choices.account.push(next);else if(/^\d{10,}$/.test(line))choices.account.push(line);const p=line.match(/(?:收款单位|收款人|收款名称|户名|企业名称|账户名称)[：:]?(.+)/);if(p)choices.payee.push(p[1]);else if(/^(收款单位|收款人|户名)$/.test(line)&&next)choices.payee.push(next);if(/银行|支行/.test(line))choices.bank.push(line.replace(/^开户(?:银行|行)[：:]?/,''));}if(!choices.payee.length){const line=lines.find(l=>/[\u4e00-\u9fff]/.test(l)&&!/银行|支行|开户|收款|账号|账户/.test(l));if(line)choices.payee.push(line);}}else{const money=clean.replace(/[\s,，￥¥元]/g,'');if(/^\d+(\.\d{1,2})?$/.test(money)){try{if(cents(money)>0n)choices.amount.push(decimal(cents(money)));}catch{}}else if(/[\u4e00-\u9fff]/.test(clean))choices.team.push(lines.join(''));}});choices.reason=[title,...choices.team].filter(Boolean).length?[ [title,...choices.team].filter(Boolean).join('｜') ]:[];Object.keys(choices).forEach(k=>choices[k]=[...new Set(choices[k])]);return choices;}
$('ocr-file').onchange=e=>run(async()=>{const file=e.target.files[0];if(!file)return;if(busy)throw Error('正在处理，请稍后再试。');if(file.size>20*1024*1024)throw Error('图片不能超过 20 MB。');if(!window.Tesseract)throw Error('识图组件未加载，请刷新网页。');busy=true;e.target.disabled=true;let worker;try{ocrValues=null;$('ocr-review').hidden=true;$('ocr-progress').textContent='正在读取图片…';const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>40000000){bitmap.close();throw Error('图片尺寸过大，请先压缩图片。');}const scale=Math.min(1,2400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const boxes=redBoxes(canvas);if(!boxes.length)throw Error('未找到完整红框，表单未修改。');if(boxes.length>30)throw Error('红框数量过多，请拆分图片后识别。');if(ocrURL)URL.revokeObjectURL(ocrURL);ocrURL=URL.createObjectURL(file);$('ocr-image').src=ocrURL;$('ocr-image').hidden=false;worker=await Tesseract.createWorker('chi_sim+eng',1,{workerPath:'https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/worker.min.js',corePath:'https://cdn.jsdelivr.net/npm/tesseract.js-core@5.1.1',logger:m=>{$('ocr-progress').textContent=`${m.status} ${Math.round((m.progress||0)*100)}%`;}});const results=[];for(let i=0;i<boxes.length;i++){const box=boxes[i],crop=document.createElement('canvas');crop.width=Math.max(1,box.w-10);crop.height=Math.max(1,box.h-10);crop.getContext('2d').drawImage(canvas,box.x+5,box.y+5,crop.width,crop.height,0,0,crop.width,crop.height);const {data}=await worker.recognize(crop);results.push({box,text:data.text});$('ocr-progress').textContent=`已识别 ${i+1} / ${boxes.length} 个红框`;}if(!results.some(r=>r.text.trim()))throw Error('红框内没有识别出文字，请换清晰图片。');ocrValues=parseOCR(results,canvas.height);$('ocr-fields').replaceChildren();for(const k of ['payee','account','bank','amount','reason','team']){const choices=ocrValues[k],wrapper=control(k,FIELDS[k]||'团队 / 项目',choices.length===1?choices[0]:'','ocr-');const input=wrapper.querySelector('input,textarea');if(choices.length>1){const select=document.createElement('select');select.setAttribute('aria-label',(FIELDS[k]||'团队')+'候选值');select.append(new Option('请选择候选值',''));choices.forEach(v=>select.append(new Option(v,v)));select.onchange=()=>input.value=select.value;wrapper.append(select);} $('ocr-fields').append(wrapper);} $('ocr-text').textContent=results.map((r,i)=>`红框 ${i+1}\n${r.text.trim()}`).join('\n\n');$('ocr-review').hidden=false;$('ocr-progress').textContent='识别完成，请逐项核对账号、金额与收款信息。';}finally{if(worker)await worker.terminate();busy=false;e.target.disabled=false;e.target.value='';}});
$('apply-ocr').onclick=()=>run(()=>{if(!ocrValues)throw Error('请先识别图片。');const data={...values(),application_date:today()};for(const k of Object.keys(ocrValues)){data[k]=$('ocr-'+k).value.trim();if(ocrValues[k].length>1&&!data[k])throw Error(`请核对${FIELDS[k]||'团队'}的多个候选值。`);}activeId=null;fill(data);persist({...state,draft:data});ocrValues=null;$('ocr-review').hidden=true;page('form');tell('已填入新申请，请核对后导出。');});
$('cancel-ocr').onclick=()=>{ocrValues=null;$('ocr-review').hidden=true;$('ocr-image').hidden=true;$('ocr-progress').textContent='';};
load();if(readable&&state.expenseDefaultVersion!==EXPENSE_DEFAULT_VERSION){if(state.draft&&!String(state.draft.expense_unit||'').trim())state.draft.expense_unit=DEFAULT_EXPENSE_UNIT;state.expenseDefaultVersion=EXPENSE_DEFAULT_VERSION;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{tell('默认报销单位已显示，但旧草稿迁移未能保存。请检查浏览器存储空间。');}}fill(state.draft||defaults());refreshOptions();if(state.draft)tell('已恢复上次未完成的草稿。');
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_payment_draft',title:'读取付款申请草稿',description:'读取当前页面已填写的付款申请，不导出、不付款。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('不接受参数');return values();}})).catch(()=>{});}catch{}}

